### ISSUE TITLE
Install Error: object ‘py_del_attr’ is not exported by 'namespace:reticulate'

### ISSUE THREAD

**Issue by LMayhew** [dynverse/anndata#2]
Using R version 3.6.2 (2019-12-12)
install.packages("anndata")

Error: object ‘py_del_attr’ is not exported by 'namespace:reticulate'

help?

**Comment by rcannood** [comment]
Hi @LMayhew!

That's a strange error. Could you try updating your R version to R 4.0?

Kind regards,
Robrecht

**Comment by asifzubair** [comment]
I was able to fix this by reinstalling `reticulate`. Probably, I had an older version of `reticulate`.

I'm using R 3.6.3

**Comment by rcannood** [comment]
Thanks @asifzubair ! It seems `py_del_attr` was added to `reticulate` in version 1.17. I'll specify `reticulate (>= 1.17)` in the DESCRIPTION to solve this issue.
