### ISSUE TITLE
adata$uns error: Conversion from numpy array type 20 is not supported

### ISSUE THREAD

**Issue by simonmfr** [dynverse/anndata#23]
Hi, I am having the same issue as in #12 when trying to load adata$uns.

```
Error in eval(expr, envir, enclos): Conversion from numpy array type 20 is not supported
Traceback:

1. (function (value) 
 . {
 .     if (missing(value)) {
 .         py_to_r_ifneedbe(private$.anndata$uns)
 .     }
 .     else {
 .         if (is.null(value)) {
 .             py_del_attr(private$.anndata, "uns")
 .         }
 .         else {
 .             private$.anndata$uns <- value
 .         }
 .         self
 .     }
 . })()
2. py_to_r_ifneedbe(private$.anndata$uns)
3. py_to_r(x)
4. py_to_r.collections.abc.Mapping(x)
5. python_builtins$dict(x)
6. py_to_r(result)
7. py_to_r.python.builtin.dict(result)
8. py_ref_to_r(x)
```

Using python anndata 0.8.0 and anndata_0.7.5.6

Any idea how to fix this? I've sent you a small h5ad file to robrecht@cannoodt.dev.

Thanks for the great package,
Simon

**Comment by simonmfr** [comment]
The bug is due to `adata.uns['rank_genes_groups']`, after deleting `rank_genes_groups` it works perfectly

**Comment by rcannood** [comment]
Indeed -- there will be certain data types that reticulate can't convert. If such occur, we need to manually remove the problematic data objects or write a converter ourselves.

Glad to hear you managed to resolve the issue yourself! Please let me know if anything else arises.
