### ISSUE TITLE
Importing anndata

### ISSUE THREAD

**Issue by akhst7** [dynverse/anndata#3]
Hi, 

With this, one can create an anndata in R API but is there any way to import the existing anndata to R environment, by some function like, ReadAnndata(file, options...) ? 

Thanks.

**Comment by rcannood** [comment]
Hi there!

Absolutely, see `read_h5ad()`.

Kind regards,
Robrecht

**Comment by akhst7** [comment]
Thanks it worked !!  But I have another related  question which I will post later.
