### ISSUE TITLE
Adding  obj items to layers 

### ISSUE THREAD

**Issue by akhst7** [dynverse/anndata#4]
Hi, 

I created an anndata obj from Seurat file by using convertFormat from a sceasy package as follows;

`convertFormat(pbmc10k.su, from = "seurat", to="anndata", outFile = "pbmc10k.h5ad")`

and imported this file back to R by using read_h5ad by

`pbmc10k.ad<-read_h5ad(filename = "/Volumes/Documents/R/pbmc10k.h5ad")`

and output of the file is as follows;

```
> pbmc10k.ad
AnnData object with n_obs × n_vars = 10194 × 36601
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.0.8', 'seurat_clusters', 'nCount_unspliced', 'nFeature_unspliced'
    var: 'name'
    obsm: 'X_pca', 'X_umap'
```
For some reasons,` $unspliced ` in the original Seurat obj, pbmc10k became obj: `'nCount_unspliced', 'nFeature_unspliced'` rather than `var: "unspliced"` and` layers:"unspliced"` during convention from the Seurat obj to anndata.  

I tried to create  layers:'unspliced' as follows;

`> pbmc10k.ad$layers["unspliced"]<-pbmc10k.ad$obs["nCount_unspliced"]`

but I got the error 

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Value passed for key 'unspliced' is of incorrect shape. Values of layers must match dimensions (0, 1) of parent. Value had shape (10194, 1) while it should have had (10194, 36601). 
6. stop(structure(list(message = "ValueError: Value passed for key 'unspliced' is of incorrect shape. Values of layers must match dimensions (0, 1) of parent. Value had shape (10194, 1) while it should have had (10194, 36601).", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x00000001126e065e _ZN4Rcpp9exceptionC2EPKcb + 222", 
    "2   reticulate.so                       0x00000001126e8735 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 53",  ... 
5. _validate_value at aligned_mapping.py#52
4. __setitem__ at aligned_mapping.py#151
3. x$.__enclos_env__$private$.layers$`__setitem__`(name, value) 
2. `[<-.LayersR6`(`*tmp*`, "unspliced", value = structure(list(nCount_unspliced = c(12648, 
7323, 10260, 1509, 12001, 6243, 4795, 5154, 15202, 6330, 11564, 
8443, 4031, 2754, 4417, 2299, 2514, 3265, 2292, 5548, 4473, 9594, 
4167, 5108, 10666, 1961, 1473, 14621, 6071, 8165, 1922, 4738,  ... 
1. `[<-`(`*tmp*`, "unspliced", value = structure(list(nCount_unspliced = c(12648, 
7323, 10260, 1509, 12001, 6243, 4795, 5154, 15202, 6330, 11564, 
8443, 4031, 2754, 4417, 2299, 2514, 3265, 2292, 5548, 4473, 9594, 
4167, 5108, 10666, 1961, 1473, 14621, 6071, 8165, 1922, 4738,  ... 
```

Vignette describes several anndata manipulation in R but I don't not sees  how to create `var:'unspliced' and layers:'unspliced'` from `obj:'nCount_unspliced', 'nFeature_unspliced'`. 

I really appreciate any help. 

Thanks.

**Comment by rcannood** [comment]
Hello @akhst7 !

Sorry for the late response.

This behaviour is caused by the `convertFormat()` function, which is indirectly because [`theislab/anndata`](github.com/theislab/anndata) doesn't support layers with different dimensions, so it all gets moved to the main var. 

Kind regards,
Robrecht
