### ISSUE TITLE
Zarr support

### ISSUE THREAD

**Issue by schienstockd** [dynverse/anndata#9]
Hello.

Out of interest, can you open and write zarr files with reticulate?
We have a an R/Shiny image analysis application and would like to store the data as zarr. We currently use scanpy and h5 which is working.
I found this github page that attempted to implement zarr for R:
https://github.com/gdkrmr/zarr-R

I'm just curious if that could "just" work with reticulate or if there is a significant technical barrier?

Thanks!

**Comment by Artur-man** [comment]
I see bindings here that call [read_zarr](https://github.com/dynverse/anndata/blob/main/R/read_zarr.R) and [write_zarr](https://github.com/dynverse/anndata/blob/main/R/write_zarr.R) methods from anndata(py), but is there a certain reason that these were commented out ?

**Comment by rcannood** [comment]
Fixed by #33 ! Will be released soon. Thanks for the reminder!
